package com.comodide.editor.model;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.EntityType;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLEntity;
import org.semanticweb.owlapi.vocab.OWLRDFVocabulary;

import com.comodide.editor.SDConstants;
import com.mxgraph.model.mxGeometry;

public class ClassCell extends ComodideCell {
	
	private static final long serialVersionUID = 4458786422295695195L;
	private static final int WIDTH = 75;
	private static final int HEIGHT = 30;
	private static final String STYLE = SDConstants.classStyle;
	private static IRI DEFAULT_IRI =  OWLRDFVocabulary.OWL_CLASS.getIRI();
	private static EntityType<OWLClass> DEFAULT_TYPE = EntityType.CLASS;
	
	/** The default constructor for this class. */
	public ClassCell() {
		this(OWLManager.getOWLDataFactory().getOWLEntity(DEFAULT_TYPE, DEFAULT_IRI),
				0.0, 0.0);
	}
	
	/**
	 * The constructor for this class.
	 * 
	 * @param owlEntity is set to the super class of this class cell.
	 * @param positionX is passed as an argument to the new geometry.
	 * @param positionY is passed as an argument to the new geometry.
	 */
	public ClassCell(OWLEntity owlEntity, double positionX, double positionY) {
		super(owlEntity);

		this.geometry = new mxGeometry(positionX, positionY, WIDTH, HEIGHT);
		this.geometry.setRelative(false);
		
		this.style = STYLE;
		
		this.vertex = true;
		this.connectable = true;
	}

	/** Returns the default IRI generated by this class. */
	public IRI defaultIRI() {
		return DEFAULT_IRI;
	}
}
